config/routes.rb
Rails.application.routes.draw do
  get 'home/tourpackages' 
  get 'home/experiences'
  get 'home/reviews'
  get 'home/blog'
  get 'home/uberuns'
  get 'home/kontakt'
  get 'home/faqs'
  get 'home/reisenplanungstarten', to: 'home#reisenplanungstarten', as: 'home_reisenplanung_starten'
  get 'home/index'

  post 'home/reisenplanungstarten', to:'home#reisenplanungstarten'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @response = flash[:response]
  end

  def tourpackages
  end

  def experiences
  end

  def reviews
  end

  def blog
  end

  def uberuns
  end

  def kontakt
  end

  def faqs
  end

  def reisenplanungstarten
  flash[:response] = "you clicked the link!"
  redirect_to root_path
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tour_helper.rb
module TourHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="light">
  <div class="container-fluid">
    <a href="<%= root_path %>">
      <%= image_tag 'marokkotravelconnection-logo.png', alt: 'Marokko Travel Connection Logo' %>
      </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', home_index_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= link_to 'Tour Packages', home_tourpackages_path, class: "nav-link dropdown-toggle", role: "button", data: { bs_toggle: "dropdown" }, aria: { expanded: "false" } %>
          <ul class="dropdown-menu">
            <li><%= link_to 'Experiences', home_experiences_path, class: 'dropdown-item' %></li>
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to 'Reviews', home_reviews_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Blog', home_blog_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Über Uns', home_uberuns_path, class: "nav-link active" %>
        </li>
        <li class="nav-item dropdown">
          <%= link_to 'Kontakt', home_kontakt_path, class: "nav-link dropdown-toggle", role: "button", data: { bs_toggle: "dropdown" }, aria: { expanded: "false" } %>
          <ul class="dropdown-menu">
            <li><%= link_to 'FAQS', home_faqs_path, class: 'dropdown-item' %></li>
          </ul>
        </li>
      </ul>
      <%= button_to "Reisenplanung starten", home_reisenplanungstarten_path, method: :post, class: "btn btn-sm btn-outline-secondary" %>
    </div>
  </div>
</nav>

          

app/views/home/index.html.erb
<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
	<div class="carousel-inner">
		<div class="carousel-item active">
			<%= image_tag "Slide1", class: 'd-block w-100', alt:"Slide1" %>
			</div>
		<div class="carousel-item">
			<%= image_tag "Slide2", class: 'd-block w-100', alt:"Slide2" %>
		</div>
		<div class="carousel-item">
			 <%= image_tag "Slide3", class:'d-block w-100', alt:"Slide3" %>
		</div>
	</div>
</div>
<br/>
<br/>
<h3>Marokko: Eine Reise für die Seele - Wilkomen bei Freunden</h3>
<br/>
<p>Stellen Sie sich vor, Sie sind nicht nur ein Reisender, sondern ein geschätzter Freund in einem Land, das seine Arme öffnet und Sie in eine Welt voller Wunder einlädt. Genau das erwartet Sie bei Marokko Travel Connection. Wir sind mehr als nur ein Reisebüro, wir sind Ihre persönlichen Freunde in Marokko, bereit, Ihnen die verborgenen Schätze und die herzliche Umarmung unserer Heimat zu zeigen.</p>
<br/>
<h3>Ihr Reisebegleiter: Ammar, ein Sohn der Wüste</h3>
<br/>
<p>Mein Name ist Ammar, und Marokko ist nicht nur mein Zuhause, es ist ein Teil meiner Seele. Als Berber, tief verwurzelt in den Traditionen und der Kultur dieses Landes, habe ich mein Leben der Aufgabe gewidmet, anderen die Schönheit und den Zauber Marokkos näherzubringen. Seit 10 Jahren teile ich meine Leidenschaft für dieses Land mit Reisenden aus aller Welt, und jetzt möchte ich Sie auf eine Reise mitnehmen, die Ihr Herz berühren wird.</p>
<br/>
<h3>Entdecken Sie das wahre Marokko – Gemeinsam mit Freunden</h3>
<br/>
<p>Was wäre eine Reise ohne Freunde, die Ihnen die Geheimnisse und verborgenen Ecken eines Ortes zeigen? Bei Marokko Travel Connection sind wir mehr als nur Reiseführer, wir sind Ihre Freunde vor Ort. Wir möchten, dass Sie Marokko so erleben, wie es die Einheimischen tun – authentisch, lebendig und voller unvergesslicher Momente.</p>
<br/>
<h3>Individualität ist unsere Stärke – Ihre Reise, Ihre Träume</h3>
<br/>
<p>Jede Reise ist so einzigartig wie die Person, die sie unternimmt. Deshalb gestalten wir Ihre Marokko-Erfahrung ganz nach Ihren Wünschen. Träumen Sie von einem romantischen Riad in Marrakesch, einer Wanderung durch das majestätische Atlasgebirge oder einem unvergesslichen Abenteuer in der Sahara? Wir machen es möglich.</p>
<br/>
<h3>Ihr Budget, Ihr Wert – Transparenz und Vertrauen</h3>
<br/>
<p>Wir wissen, dass eine Reise eine Investition ist, sowohl finanziell als auch emotional. Deshalb legen wir größten Wert auf Transparenz und Ehrlichkeit. Wir beraten Sie offen und ehrlich über die Kosten Ihrer Reise und stellen sicher, dass Sie das beste Preis-Leistungs-Verhältnis erhalten. Ihr Vertrauen ist uns heilig, und wir setzen alles daran, dass Ihre Investition in eine unvergessliche Marokko-Reise sich lohnt.</p>
<br/>
<h3>In Marokko – Ihr Willkommen Abenteuer beginnt jetzt</h3>
<br/>
<p>Egal, ob Sie alleine reisen, als Paar oder in einer Gruppe, ob Sie ein luxuriöses Hotel oder ein gemütliches Apartment bevorzugen, wir haben die perfekte Lösung für Sie. Teilen Sie uns einfach Ihre Wünsche mit, und wir kreieren gemeinsam eine Reise, die Ihre Erwartungen übertrifft.</p>
<br/>
<h3>Marokko wartet auf Sie – Kommen Sie und erleben Sie die Magie</h3>
<br/>
<p>Schließen Sie die Augen und stellen Sie sich vor, wie der warme Sand der Sahara Ihre Füße umschmeichelt, wie der Duft exotischer Gewürze Ihre Sinne betört und wie das herzliche Lachen der Menschen Ihr Herz erwärmt. Das ist Marokko, und wir laden Sie ein, es mit uns zu entdecken.</p>
<br/>
<h3>Ihr Abenteuer beginnt jetzt – Kontaktieren Sie uns noch heute!</h3>
<div class="container">
  <%= button_to "Reisenplanung starten", home_reisenplanungstarten_path, method: :post, class: "btn btn-sm btn-outline-secondary" %>
  <% if @response.present? %>
    <p><%= @response %></p>
  <% end %>
</div>

app/views/home/uberuns.html.erb
<h3>Willkommen in meiner Welt – Marokko! </h3>
<br/>
<p>Hallo mein Freund, ich bin Ammar, dein persönlicher Marokko Führer. Geboren und aufgewachsen im Herzen dieser atemberaubenden Landschaft, kenne ich ihre Geheimnisse wie kein anderer. Als leidenschaftlicher Entdecker liebe ich es, meine Begeisterung mit Menschen aus aller Welt zu teilen und freue mich darauf, auch dich in ihren Bann zu ziehen.</p>
<p>Was mich am meisten an meiner Arbeit begeistert:</p>
<p>● Das Abenteuer: Jede Tour ist eine neue Expedition, gefüllt mit
unvergesslichen Momenten und unerwarteten Begegnungen.</p>
<p>● Die Menschen: Ich liebe es, Reisende aus verschiedenen Kulturen
kennenzulernen, ihre Geschichten zu hören und ihnen meine Heimat zu
zeigen.</p>
<p>● Das Lernen: Jede Interaktion ist eine Chance, voneinander zu lernen – sei es
über Traditionen, Sprachen oder einfach das Leben.</p>
<p>● Die Gemeinschaft: Die Wüste ist mehr als nur Sand und Steine. Sie ist eine
lebendige Gemeinschaft, in der jeder Einzelne dazu beiträgt, dieses
empfindliche Ökosystem zu schützen und zu erhalten.</p>
<p>Als dein persönlicher Guide werde ich, zusammen mit meinem engagierten Team,
eine Reise gestalten, die auf deine individuellen Wünsche zugeschnitten ist. Wir
bringen dich zu den faszinierendsten Orten der Wüste, halten deine Erinnerungen in
atemberaubenden Fotos fest und sorgen dafür, dass deine Reise mühelos verläuft.
Von aufregenden Kamelritten durch die Dünen bis hin zum Nervenkitzel des 
Sandboardens oder Jet-Ski-Fahrens – wir lassen deine Träume wahr werden.</p>
</br>
<h6>Ein Einblick in das Leben in der Wüste:</h6>
<p>Die Wüste ist mein Zuhause, mein Zufluchtsort und meine größte Inspiration. Ich
liebe die friedliche Stille, die klare Luft und die endlose Weite, die den Geist zur
Ruhe kommen lässt. Die Schönheit der Wüste offenbart sich in den ständig
wechselnden Farben der Dünen, im Spiel von Licht und Schatten und in den
geheimnisvollen Geräuschen der Nacht.</p>
<p>Das Leben hier ist einfach, aber reich an einzigartigen Erfahrungen. Wir sammeln
Wasser, kochen auf traditionelle Weise, hüten unsere Tiere und finden Trost und
Wärme in der Gemeinschaft. Besonders magisch sind die Abende am Lagerfeuer,
wenn Geschichten erzählt, Lieder gesungen und Erinnerungen geschaffen werden.
Während deiner Reise wirst du Teil unserer Großfamilie werden, gemeinsam lachen
und Geschichten teilen, während wir dieses außergewöhnliche Land erkunde</p>
</br>
<h6>Mein Versprechen an dich:</h6>
<p>Ich möchte, dass du die Wüste mit allen Sinnen erlebst – ihre Schönheit, ihre Ruhe,
ihre Herausforderungen und ihre reiche Kultur. Ich werde dich sicher durch diese
faszinierende Landschaft führen, dir ihre Geheimnisse enthüllen und dafür sorgen,
dass du dich auf Schritt und Tritt glücklich fühlst.</p>
<br/>
<h6>Praktische Tipps für deine Wüstenreise:</h6>
<p>● Die Wüste ist im Allgemeinen sicher, aber halte dich nachts in der Nähe
deines Lagers auf, um nicht versehentlich in Grenzgebiete zu geraten.</p>
<p>● Respektiere die Umwelt und hilf uns, die Wüste sauber zu halten.</p>
<p>● Sei offen für neue Erfahrungen und lass dich von der Magie der Wüste
verzaubern!</p>
<br/>
<h6>Worauf wartest du noch? Lass uns gemeinsam die Wunder der Wüste
entdecken!</h6>
<br/>
<h6>Dein Ammar</h6>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="de-DE">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <title>Marokko Travel Connection</title>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_importmap_tags %>

  </head>
  <body>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@poperjs/core@2.9.3/dist/umd/popper.min.js"></script>



    <%= render 'home/header' %>
    <div class="container">
      <br/>
      <%= yield %>
    </div>


    <footer>
      Marokko Travel Connection; &copy 2024
    </footer>

  </body>
</html>

app/views/tour/experiences.html.erb
<h1>Tour#experiences</h1>
<p>Find me in app/views/tour/experiences.html.erb</p>

app/views/tour/kontakt.html.erb
<h1>Tour#kontakt</h1>
<p>Find me in app/views/tour/kontakt.html.erb</p>

app/views/tour/packages.html.erb
<h1>Tour#packages</h1>
<p>Find me in app/views/tour/packages.html.erb</p>

app/views/tour/reviews.html.erb
<h1>Tour#reviews</h1>
<p>Find me in app/views/tour/reviews.html.erb</p>

app/views/tour/uber.html.erb
<h1>Tour#uber</h1>
<p>Find me in app/views/tour/uber.html.erb</p>

app/views/tour/uns.html.erb
<h1>Tour#uns</h1>
<p>Find me in app/views/tour/uns.html.erb</p>